### ISSUE TITLE
Exception thrown with invalid data in Redis

### ISSUE THREAD

**Issue by skandragon** [spinnaker/kayenta#224]
I have nothing related to redis in my kayenta-local.yml config file, and this repeats:

```
com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.netflix.spinnaker.orca.q.redis.RedisActiveExecutionsMonitor$ActiveExecution: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: {"id":"964b91c9-e6cd-42eb-87ae-9d438c8c44d3","type":"PIPELINE","application":"kayenta-d6755142-6194-4464-b55e-f0d2e08aba9c@thunderbarrow.corp.netflix.com"}; line: 1, column: 2]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1456) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1012) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1206) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842) ~[jackson-databind-2.8.8.jar:2.8.8]
	at com.netflix.spinnaker.orca.q.redis.RedisActiveExecutionsMonitor.getActiveExecutions(RedisActiveExecutionsMonitor.kt:150) ~[orca-queue-redis-5.5.0.jar:5.5.0]
	at com.netflix.spinnaker.orca.q.redis.RedisActiveExecutionsMonitor.snapshotActivity(RedisActiveExecutionsMonitor.kt:75) ~[orca-queue-redis-5.5.0.jar:5.5.0]
	at com.netflix.spinnaker.orca.q.redis.RedisActiveExecutionsMonitor.registerGauges(RedisActiveExecutionsMonitor.kt:64) ~[orca-queue-redis-5.5.0.jar:5.5.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511) [na:1.8.0_144]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java) [na:1.8.0_144]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
```

**Comment by skandragon** [comment]
I believe this was fixed by a recent Orca change I made; closing unless it rears is head again.
