### ISSUE TITLE
compile err

### ISSUE THREAD

**Issue by iqiyiadsrv** [spinnaker/kayenta#358]
I get response below when compile v1.09 with './gradlew':
> Failed to apply plugin [class 'com.netflix.spinnaker.gradle.project.SpinnakerProjectConventionsPlugin']
   > index is out of range 0..-1 (index = 0)
when compile with './gradlew -DDEBUG=true':
Caused by: java.lang.IndexOutOfBoundsException: index is out of range 0..-1 (index = 0)
        at nebula.plugin.netflixossproject.publishing.PublishingPlugin.calculateUrlFromOrigin(PublishingPlugin.groovy:75)
        at nebula.plugin.netflixossproject.publishing.PublishingPlugin$calculateUrlFromOrigin.call(Unknown Source)
        at com.netflix.spinnaker.gradle.project.SpinnakerProjectConventionsPlugin.apply(SpinnakerProjectConventionsPlugin.groovy:53)
        at com.netflix.spinnaker.gradle.project.SpinnakerProjectConventionsPlugin.apply(SpinnakerProjectConventionsPlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
        at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:44)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
        ... 78 more

**Comment by duftler** [comment]
Do your git remotes include the `.git` at the end of the url? Like this: `git@github.com:spinnaker/kayenta.git`

I think that error might be related to neglecting to include the `.git` suffix.

**Comment by iqiyiadsrv** [comment]
Thanks, your are right, It's only work with git clone but download the zip.
