### ISSUE TITLE
Support Basic Auth for metric backends

### ISSUE THREAD

**Issue by Remz-Jay** [spinnaker/kayenta#456]
In our case, specifically for the Prometheus backend.

Our Prometheus installations are protected by AAA to ensure we don't have unauthorized access to our metrics. To allow system accounts to access to Prometheus, we have al alternate Kubernetes Ingress that serves the "prometheus-api" endpoint, which is protected by Basic Auth.

As such, Spinnaker/Kayenta needs to use this endpoint and provide basic auth credentials. I've done so by adding them to the `--base-url` argument in https://github.com/spinnaker/halyard/blob/master/docs/commands.md#hal-config-canary-prometheus-account-add .

After that deploys, Kayenta fails with the following error:

```
2019-01-07 14:37:41.197  INFO 1 --- [pool-1-thread-1] c.n.s.o.t.RedisActiveExecutionsMonitor   : Refreshing active execution gauges (active: 0)
2019-01-07 14:37:53.624  INFO 1 --- [    scheduler-2] c.n.k.p.service.PrometheusRemoteService  : ---> HTTP GET https://spinnaker:password@prometheus-api.some.domain/api/v1/label/__name__/values
2019-01-07 14:37:53.715  INFO 1 --- [    scheduler-2] c.n.k.p.service.PrometheusRemoteService  : <--- HTTP 401 https://spinnaker:password@prometheus-api.some.domain/api/v1/label/__name__/values (90ms)
2019-01-07 14:37:53.717 ERROR 1 --- [    scheduler-2] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

retrofit.RetrofitError: 401 Unauthorized
  at retrofit.RetrofitError.httpError(RetrofitError.java:40) ~[retrofit-1.9.0.jar:na]
  at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388) ~[retrofit-1.9.0.jar:na]
  at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[retrofit-1.9.0.jar:na]
  at com.sun.proxy.$Proxy96.listMetricDescriptors(Unknown Source) ~[na:na]
  at com.netflix.kayenta.prometheus.metrics.PrometheusMetricsService.updateMetricDescriptorsCache(PrometheusMetricsService.java:337) ~[kayenta-prometheus.jar:na]
  at sun.reflect.GeneratedMethodAccessor140.invoke(Unknown Source) ~[na:na]
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
  at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
  at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.20.RELEASE.jar:4.3.20.RELEASE]
  at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.20.RELEASE.jar:4.3.20.RELEASE]
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_181]
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_181]
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_181]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
  at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
```
(password and URL changed for obvious reasons)

If I `kubectl exec` into the Kayenta pod and manually `wget` the URL mentioned in the error, authentication succeeds, and I receive the information as expected.

Looks to me that credentials passed in the `--base-url` are not passed as headers during the request,  failing the basic auth. 

Given this class + comment: https://github.com/spinnaker/kayenta/blob/master/kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/security/PrometheusCredentials.java#L28 , it seems that some work has been done on providing basic auth for this backend. 

What would need to happen to make it work?

**Comment by duftler** [comment]
Still need to add halyard support for these new attributes.

**Comment by duftler** [comment]
Halyard support is here: https://github.com/spinnaker/halyard/pull/1150

**Comment by duftler** [comment]
Both PR's are merged.
