### ISSUE TITLE
RedisClientNotFound when trying to Building and Run Kayenta

### ISSUE THREAD

**Issue by SPawar** [spinnaker/kayenta#724]
I followed steps based on Kayenta docs: https://github.com/spinnaker/kayenta/blob/master/docs/building-and-running-kayenta.md

I have redis-server running and ready to accept connections but when I run `java -jar kayenta-web/build/libs/kayenta-web.jar` I am getting the following exception. Would appreciate any help to resolve this issue. 

`Caused by: com.netflix.spinnaker.kork.jedis.exception.RedisClientNotFound: Could not find primary Redis client by name 'executionRepository' and no default configured
	at com.netflix.spinnaker.kork.jedis.RedisClientSelector.lambda$primary$1(RedisClientSelector.java:54) ~[kork-jedis-7.41.1.jar!/:na]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_242]
	at com.netflix.spinnaker.kork.jedis.RedisClientSelector.primary(RedisClientSelector.java:52) ~[kork-jedis-7.41.1.jar!/:na]
	at com.netflix.spinnaker.kork.jedis.RedisClientSelector.primary(RedisClientSelector.java:43) ~[kork-jedis-7.41.1.jar!/:na]`

**Comment by fieldju** [comment]
Do you have your config file in `~/.spinnaker` or configure spring to point to a different dir?
I think you can add `--debug` as an arg to the jar to get more info from Springboot.

**Comment by SPawar** [comment]
I didnt have kayenta.yaml config file in ~/.spinnaker. Moving the config file to ~/.spinnaker fixed the issue. Thanks!
