### ISSUE TITLE
Canary Analysis Prometheus Query Parsing Error

### ISSUE THREAD

**Issue by tonyg4864** [spinnaker/kayenta#821]
### Issue Summary:
I am currently facing an issue with the "Canary Analysis" stage and the Canary Config. It seems that the Canary Analysis process cannot parse the provided Prometheus query.

### Cloud Provider(s):
Kubernetes

### Environment:

1. Spinnaker v1.20.8

### Feature Area:

- Kayenta
- Prometheus Metrics Provider

### Description:

- I am currently facing an issue with the "Canary Analysis" stage. It seems that Spinnaker cannot parse the Prometheus query properly. My prometheus query uses the `!~` operator and it looks something like this: `path!~"/health|/blah"`

- The Kayenta log output looks something like this: 

```2020-11-30 23:05:38.252  INFO 1 --- [    handlers-20] c.n.k.p.service.PrometheusRemoteService  : <--- HTTP 400 http://prom-metrics-provider-host.net/api/v1/query_range?query=histogram_quantile%280.95%2C+sum%28rate%28app_request_latency_histogram_bucket%7Bnamespace%3D%22foo-bar%22%2C+name%3D%22myapp-0-0-2%22%2C+env%3D%7E%22in-cluster_dev-int%22%7D%2C+path%21%7E%22%2Fhealth%7C%2Fprometheus%7C%2Ffavicon.ico%22%7D%5B1m%5D%29%29+by+%28le%2C+path%29%29&start=2020-11-30T23%3A03%3A29.646449Z&end=2020-11-30T23%3A05%3A29.646451Z&step=1 (77ms)
2020-11-30 23:05:39.471 ERROR 1 --- [    handlers-20] c.n.s.orca.q.handler.RunTaskHandler      : Error running PrometheusFetchTask for pipeline[01ERDPET9N7ETCF8WNA4Z58G2D]

retrofit.RetrofitError: 400 Bad Request
	at retrofit.RetrofitError.httpError(RetrofitError.java:40) ~[retrofit-1.9.0.jar:na]
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388) ~[retrofit-1.9.0.jar:na]
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[retrofit-1.9.0.jar:na]
	at com.sun.proxy.$Proxy148.rangeQuery(Unknown Source) ~[na:na]
	at com.netflix.kayenta.prometheus.metrics.PrometheusMetricsService.queryMetrics(PrometheusMetricsService.java:260) ~[kayenta-prometheus.jar:na]
	at com.netflix.kayenta.metrics.SynchronousQueryProcessor.executeQuery(SynchronousQueryProcessor.java:88) ~[kayenta-core.jar:na]
	at com.netflix.kayenta.metrics.SynchronousQueryProcessor.processQueryAndReturnMap(SynchronousQueryProcessor.java:189) ~[kayenta-core.jar:na]
	at com.netflix.kayenta.metrics.SynchronousQueryProcessor.executeQueryAndProduceTaskResult(SynchronousQueryProcessor.java:204) ~[kayenta-core.jar:na]
	at com.netflix.kayenta.prometheus.orca.PrometheusFetchTask.execute(PrometheusFetchTask.java:97) ~[kayenta-prometheus.jar:na]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:130) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2$1.invoke(RunTaskHandler.kt:73) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withLoggingContext(RunTaskHandler.kt:379) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.access$withLoggingContext(RunTaskHandler.kt:73) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:128) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1$2.invoke(RunTaskHandler.kt:73) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$sam$java_util_concurrent_Callable$0.call(AuthenticationAware.kt) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$0(AuthenticatedRequest.java:92) ~[kork-security-7.31.1.jar:7.31.1]
	at com.netflix.spinnaker.orca.q.handler.AuthenticationAware$DefaultImpls.withAuth(AuthenticationAware.kt:51) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withAuth(RunTaskHandler.kt:73) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:127) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$handle$1.invoke(RunTaskHandler.kt:73) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:209) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler$withTask$1.invoke(RunTaskHandler.kt:73) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:68) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withTask$1.invoke(OrcaMessageHandler.kt:46) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:85) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$withStage$1.invoke(OrcaMessageHandler.kt:46) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withExecution(OrcaMessageHandler.kt:95) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withExecution(RunTaskHandler.kt:73) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withStage(OrcaMessageHandler.kt:74) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withStage(RunTaskHandler.kt:73) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.withTask(OrcaMessageHandler.kt:60) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:73) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.withTask(RunTaskHandler.kt:202) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:88) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.handle(RunTaskHandler.kt:73) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.q.MessageHandler$DefaultImpls.invoke(MessageHandler.kt:36) ~[keiko-core-3.5.0.jar:3.5.0]
	at com.netflix.spinnaker.orca.q.handler.OrcaMessageHandler$DefaultImpls.invoke(OrcaMessageHandler.kt) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.handler.RunTaskHandler.invoke(RunTaskHandler.kt:73) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.orca.q.audit.ExecutionTrackingMessageHandlerPostProcessor$ExecutionTrackingMessageHandlerProxy.invoke(ExecutionTrackingMessageHandlerPostProcessor.kt:69) ~[orca-queue-8.3.0.jar:8.3.0]
	at com.netflix.spinnaker.q.QueueProcessor$callback$1$1.run(QueueProcessor.kt:89) ~[keiko-core-3.5.0.jar:3.5.0]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]```

### Steps to Reproduce:
1. Create a canary config that executes a Prometheus Query that includes the `!~` operator. This operator is for "Selecting labels that do not regex-match the provided string".
2. Execute a canary analysis stage. 
3. Notice that the Canary Analysis stage fails with the following error:

`{"status":"error","errorType":"bad_data","error":"1:162: parse error: unexpected character after '!': '~'"}`

![Prometheus Query Parsing Error](https://user-images.githubusercontent.com/25211037/100678406-e858c080-3321-11eb-8683-1f201265b5ce.png)

**Comment by tonyg4864** [comment]
After reviewing carefully my prometheus query I found that the issue was due to a typo from my side. This is not an issue therefore I'm closing it.
